language: android
android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

  script:
    - ./gradlew app:clean app:testDebugUnitTest app:test --continue --no-daemon
