language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

  script:
    - ./gradlew app:clean app:testDebugUnitTest app:test --continue --no-daemon
